---
name: grammarly-languageserver
description: A language server implementation on top of Grammarly's SDK.
homepage: https://github.com/znck/grammarly
licenses:
  - MIT
languages:
  - Markdown
  - Text
categories:
  - LSP

source:
  id: pkg:npm/@emacs-grammarly/grammarly-languageserver@0.2.1

schemas:
  lsp: vscode:https://raw.githubusercontent.com/znck/grammarly/main/extension/package.json

bin:
  grammarly-languageserver: npm:grammarly-languageserver
